services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  pdf-generator-test:
    build: .
    entrypoint: yarn test
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres
      - TYPEORM_USERNAME=user
      - TYPEORM_PASSWORD=password
      - TYPEORM_DATABASE=pdf-generator
      - TYPEORM_PORT=5432
      - TYPEORM_ENTITIES=src/entities/**/*.ts
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./node_modules:/app/node_modules
    depends_on:
      - postgres

volumes:
  postgres-data:
