services:
  postgres:
    image: postgres:13.3
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pdf-generator:
    build: .
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./env/pdf-generator.env
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    depends_on:
      - postgres

volumes:
  postgres-data:
