services:
  postgres-test:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=pdf-generator-test

  pdf-generator-test:
    build: .
    cap_add:
      - SYS_ADMIN
    entrypoint: yarn test
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=postgres-test
      - TYPEORM_USERNAME=test
      - TYPEORM_PASSWORD=test
      - TYPEORM_DATABASE=pdf-generator-test
      - TYPEORM_PORT=5432
      - TYPEORM_ENTITIES=src/entities/**/*.ts
    volumes:
      - node-modules-test:/app/node_modules
    depends_on:
      - postgres-test

volumes:
  node-modules-test:
