services:
  postgres:
    image: postgres:13.3
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pdf-generator:
    build: .
    init: true
    cap_add:
      - SYS_ADMIN
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:9229:9229
    env_file:
      - ./env/pdf-generator.env
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    restart: always
    depends_on:
      - postgres

volumes:
  postgres-data:
  node-modules:
